// Generated by scripts/build-icon-font.py. Do not edit.
//
// Each icon is one character of RESOURCE_ID_ICONFONT. Draw one with
// fctx_draw_string(&fctx, ICON_DAY_SUNNY, s_icon_font, ...) -- the glyphs
// are normalised to a 1536/2048 em square, so the cap height set on the
// context is the height the icon comes out.

#ifndef FACEOFF_ICONS_H
#define FACEOFF_ICONS_H

#define ICON_DAY_SUNNY        "A"  // wi-day-sunny (U+F00D)
#define ICON_NIGHT_CLEAR      "B"  // wi-night-clear (U+F02E)
#define ICON_DAY_CLOUDY       "C"  // wi-day-cloudy (U+F002)
#define ICON_NIGHT_ALT_CLOUDY "D"  // wi-night-alt-cloudy (U+F086)
#define ICON_CLOUD            "E"  // wi-cloud (U+F041)
#define ICON_RAIN             "F"  // wi-rain (U+F019)
#define ICON_SNOW             "G"  // wi-snow (U+F01B)
#define ICON_FOG              "H"  // wi-fog (U+F014)
#define ICON_THUNDERSTORM     "I"  // wi-thunderstorm (U+F01E)
#define ICON_NA               "J"  // wi-na (U+F07B)
#define ICON_STEPS            "K"  // material:steps (Material Symbols)
#define ICON_FAVORITE         "L"  // material:favorite (Material Symbols)

#endif
