// Generated by scripts/build-weather-font.py. Do not edit.
//
// Each icon is one character of RESOURCE_ID_WEATHERFONT. Draw one with
// fctx_draw_string(&fctx, WI_DAY_SUNNY, s_weather_font, ...) -- the glyphs
// are normalised to a 1536/2048 em square, so the cap height set on the
// context is the height the icon comes out.

#ifndef FACEOFF_WEATHER_ICONS_H
#define FACEOFF_WEATHER_ICONS_H

#define WI_DAY_SUNNY        "A"  // U+F00D wi-day-sunny
#define WI_NIGHT_CLEAR      "B"  // U+F02E wi-night-clear
#define WI_DAY_CLOUDY       "C"  // U+F002 wi-day-cloudy
#define WI_NIGHT_ALT_CLOUDY "D"  // U+F086 wi-night-alt-cloudy
#define WI_CLOUD            "E"  // U+F041 wi-cloud
#define WI_RAIN             "F"  // U+F019 wi-rain
#define WI_SNOW             "G"  // U+F01B wi-snow
#define WI_FOG              "H"  // U+F014 wi-fog
#define WI_THUNDERSTORM     "I"  // U+F01E wi-thunderstorm
#define WI_NA               "J"  // U+F07B wi-na

#endif
